### ISSUE TITLE
workflow - add scheduled container registry cleanup

### ISSUE THREAD

**Issue by julie-ng** [julie-ng/cloud-architecture-review-app#8]
### Problem

Azure Container Registry will get full if we don't clean up unused

### Solution

- Create a GitHub Workflow to regularly purge images except for last 5, e.g. below
- Prefer GitHub over Azure feature to have automation transparency and records here

```
DRY_RUN="acr purge \
  --filter 'frontend:dev-*' \
  --untagged \
  --ago 14d \
  --keep 5 \
  --dry-run"

echo $DRY_RUN

az acr run \
  --cmd "$DRY_RUN" \
  --registry aksarchitect \
  /dev/null
```

### References

- https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auto-purge

**Comment by julie-ng** [comment]
Done

**Comment by naioja** [comment]
Do you want to introduce a schedule at ACR level or you do this at every pipeline run ?

**Comment by julie-ng** [comment]
I prefer pipelines because then I have a nice overview of all the activity around my workloads at the source (code). I'm constantly nostalgic for Jenkins dashboards on TVs…

Also I don't care to traverse the [az acr task](https://docs.microsoft.com/en-us/cli/azure/acr/task?view=azure-cli-latest) commands just to see what it's doing. Nor do I care for the disjointed Azure portal 😜
